[2023-11-21T01:00:34.317+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T01:00:34.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T01:00:34.376+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:00:34.442+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-17 00:00:00+00:00
[2023-11-21T01:00:34.488+0000] {standard_task_runner.py:57} INFO - Started process 265 to run task
[2023-11-21T01:00:34.512+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'scheduled__2023-11-17T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpdp5nunta']
[2023-11-21T01:00:34.575+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask load_outcome_types_dim
[2023-11-21T01:00:34.894+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [running]> on host bf1573643830
[2023-11-21T01:00:41.444+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_outcome_types_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-17T00:00:00+00:00'
[2023-11-21T01:00:46.929+0000] {logging_mixin.py:154} INFO - dim_outcome_types loaded
[2023-11-21T01:00:46.940+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T01:00:47.038+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=load_outcome_types_dim, execution_date=20231117T000000, start_date=20231121T010034, end_date=20231121T010047
[2023-11-21T01:00:47.440+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T01:00:47.675+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T03:57:22.419+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T03:57:22.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T03:57:22.487+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T03:57:22.539+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-17 00:00:00+00:00
[2023-11-21T03:57:22.576+0000] {standard_task_runner.py:57} INFO - Started process 780 to run task
[2023-11-21T03:57:22.627+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'scheduled__2023-11-17T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmppn0twbar']
[2023-11-21T03:57:22.678+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask load_outcome_types_dim
[2023-11-21T03:57:23.016+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [running]> on host a0f615083db8
[2023-11-21T03:57:27.999+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_outcome_types_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-17T00:00:00+00:00'
[2023-11-21T03:57:28.422+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_outcome_types_pkey"
DETAIL:  Key (outcome_type_id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/load.py", line 20, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists="append", index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dim_outcome_types_pkey"
DETAIL:  Key (outcome_type_id)=(1) already exists.

[SQL: INSERT INTO dim_outcome_types (outcome_type, outcome_type_id) VALUES (%(outcome_type)s, %(outcome_type_id)s)]
[parameters: ({'outcome_type': 'Rto-Adopt', 'outcome_type_id': 1}, {'outcome_type': 'Adoption', 'outcome_type_id': 2}, {'outcome_type': 'Euthanasia', 'outcome_type_id': 3}, {'outcome_type': 'Transfer', 'outcome_type_id': 4}, {'outcome_type': 'Return to Owner', 'outcome_type_id': 5}, {'outcome_type': 'Died', 'outcome_type_id': 6}, {'outcome_type': 'Disposal', 'outcome_type_id': 7}, {'outcome_type': 'Missing', 'outcome_type_id': 8}  ... displaying 10 of 11 total bound parameter sets ...  {'outcome_type': 'N/A', 'outcome_type_id': 10}, {'outcome_type': 'Stolen', 'outcome_type_id': 11})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-21T03:57:28.533+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load_outcome_types_dim, execution_date=20231117T000000, start_date=20231121T035722, end_date=20231121T035728
[2023-11-21T03:57:28.702+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task load_outcome_types_dim ((psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dim_outcome_types_pkey"
DETAIL:  Key (outcome_type_id)=(1) already exists.

[SQL: INSERT INTO dim_outcome_types (outcome_type, outcome_type_id) VALUES (%(outcome_type)s, %(outcome_type_id)s)]
[parameters: ({'outcome_type': 'Rto-Adopt', 'outcome_type_id': 1}, {'outcome_type': 'Adoption', 'outcome_type_id': 2}, {'outcome_type': 'Euthanasia', 'outcome_type_id': 3}, {'outcome_type': 'Transfer', 'outcome_type_id': 4}, {'outcome_type': 'Return to Owner', 'outcome_type_id': 5}, {'outcome_type': 'Died', 'outcome_type_id': 6}, {'outcome_type': 'Disposal', 'outcome_type_id': 7}, {'outcome_type': 'Missing', 'outcome_type_id': 8}  ... displaying 10 of 11 total bound parameter sets ...  {'outcome_type': 'N/A', 'outcome_type_id': 10}, {'outcome_type': 'Stolen', 'outcome_type_id': 11})]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 780)
[2023-11-21T03:57:28.870+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T03:57:29.024+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T04:17:54.168+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:17:54.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:17:54.267+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T04:17:54.403+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-17 00:00:00+00:00
[2023-11-21T04:17:54.435+0000] {standard_task_runner.py:57} INFO - Started process 393 to run task
[2023-11-21T04:17:54.453+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'scheduled__2023-11-17T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp02kn3p17']
[2023-11-21T04:17:54.468+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask load_outcome_types_dim
[2023-11-21T04:17:54.744+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [running]> on host dc3ce06c67c1
[2023-11-21T04:18:11.072+0000] {local_task_job_runner.py:228} INFO - Task exited with return code -9
[2023-11-21T04:18:12.024+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T04:47:17.023+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:47:17.033+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:47:17.034+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T04:47:17.050+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-17 00:00:00+00:00
[2023-11-21T04:47:17.069+0000] {standard_task_runner.py:57} INFO - Started process 303 to run task
[2023-11-21T04:47:17.081+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'scheduled__2023-11-17T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpm1e9z804']
[2023-11-21T04:47:17.092+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask load_outcome_types_dim
[2023-11-21T04:47:17.232+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [running]> on host de20a855d915
[2023-11-21T04:47:19.469+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_outcome_types_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-17T00:00:00+00:00'
[2023-11-21T04:47:20.296+0000] {logging_mixin.py:154} INFO - dim_outcome_types loaded
[2023-11-21T04:47:20.298+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T04:47:20.738+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=load_outcome_types_dim, execution_date=20231117T000000, start_date=20231121T044717, end_date=20231121T044720
[2023-11-21T04:47:20.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T04:47:21.060+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T04:57:58.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:57:58.926+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [queued]>
[2023-11-21T04:57:58.927+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T04:57:58.961+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_outcome_types_dim> on 2023-11-17 00:00:00+00:00
[2023-11-21T04:57:58.988+0000] {standard_task_runner.py:57} INFO - Started process 352 to run task
[2023-11-21T04:57:59.017+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_outcome_types_dim', 'scheduled__2023-11-17T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpshugt_tr']
[2023-11-21T04:57:59.039+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask load_outcome_types_dim
[2023-11-21T04:57:59.291+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_outcome_types_dim scheduled__2023-11-17T00:00:00+00:00 [running]> on host 921d770aa62c
[2023-11-21T04:58:02.799+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_outcome_types_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-17T00:00:00+00:00'
[2023-11-21T04:58:03.296+0000] {logging_mixin.py:154} INFO - dim_outcome_types loaded
[2023-11-21T04:58:03.298+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T04:58:03.359+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=load_outcome_types_dim, execution_date=20231117T000000, start_date=20231121T045758, end_date=20231121T045803
[2023-11-21T04:58:03.552+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T04:58:03.736+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
