[2023-11-17T03:18:56.846+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-17T03:18:48.266624+00:00 [queued]>
[2023-11-17T03:18:56.851+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-17T03:18:48.266624+00:00 [queued]>
[2023-11-17T03:18:56.852+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-17T03:18:56.858+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-17 03:18:48.266624+00:00
[2023-11-17T03:18:56.863+0000] {standard_task_runner.py:57} INFO - Started process 1044 to run task
[2023-11-17T03:18:56.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'manual__2023-11-17T03:18:48.266624+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmph5qi7yne']
[2023-11-17T03:18:56.870+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask transform
[2023-11-17T03:18:56.903+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform manual__2023-11-17T03:18:48.266624+00:00 [running]> on host cdede745d4f1
[2023-11-17T03:18:57.264+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T03:18:48.266624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-17T03:18:48.266624+00:00'
[2023-11-17T03:18:58.227+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:67: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['ts'] = pd.to_datetime(data.DateTime)

[2023-11-17T03:19:06.131+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 31, in transform_data
    dim_animals.to_parquet(target_dir+'dim_animals.parquet')
NameError: name 'dim_animals' is not defined
[2023-11-17T03:19:06.154+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231117T031848, start_date=20231117T031856, end_date=20231117T031906
[2023-11-17T03:19:06.173+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task transform (name 'dim_animals' is not defined; 1044)
[2023-11-17T03:19:06.224+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-17T03:19:06.240+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
