[2023-11-17T01:32:37.104+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:32:37.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:32:37.108+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:32:37.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:32:37.120+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:32:37.114+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:32:37.121+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:32:37.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.042 seconds
[2023-11-17T01:33:07.537+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:33:07.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:33:07.541+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:33:07.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:33:07.547+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:33:07.545+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:33:07.547+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:33:07.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.030 seconds
[2023-11-17T01:33:37.923+0000] {processor.py:157} INFO - Started process (PID=378) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:33:37.926+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:33:37.931+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:33:37.931+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:33:37.940+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:33:37.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:33:37.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:33:37.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.066 seconds
[2023-11-17T01:34:08.399+0000] {processor.py:157} INFO - Started process (PID=387) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:34:08.402+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:34:08.406+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:34:08.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:34:08.414+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:34:08.412+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:34:08.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:34:08.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T01:34:38.830+0000] {processor.py:157} INFO - Started process (PID=396) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:34:38.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:34:38.839+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:34:38.838+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:34:38.848+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:34:38.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:34:38.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:34:38.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.051 seconds
[2023-11-17T01:35:09.202+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:35:09.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:35:09.211+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:35:09.210+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:35:09.218+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:35:09.216+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:35:09.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:35:09.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.045 seconds
[2023-11-17T01:35:39.640+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:35:39.642+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:35:39.648+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:35:39.648+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:35:39.656+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:35:39.654+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:35:39.656+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:35:39.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.040 seconds
[2023-11-17T01:36:10.068+0000] {processor.py:157} INFO - Started process (PID=423) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:36:10.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:36:10.076+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:36:10.075+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:36:10.084+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:36:10.082+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:36:10.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:36:10.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.045 seconds
[2023-11-17T01:36:40.556+0000] {processor.py:157} INFO - Started process (PID=432) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:36:40.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:36:40.564+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:36:40.563+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:36:40.573+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:36:40.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:36:40.574+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:36:40.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T01:37:11.040+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:37:11.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:37:11.053+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:37:11.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:37:11.067+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:37:11.062+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:37:11.068+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:37:11.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.056 seconds
[2023-11-17T01:37:41.535+0000] {processor.py:157} INFO - Started process (PID=450) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:37:41.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:37:41.542+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:37:41.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:37:41.549+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:37:41.547+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:37:41.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:37:41.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.059 seconds
[2023-11-17T01:38:12.005+0000] {processor.py:157} INFO - Started process (PID=459) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:38:12.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:38:12.013+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:38:12.012+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:38:12.021+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:38:12.019+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:38:12.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:38:12.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.041 seconds
[2023-11-17T01:38:42.504+0000] {processor.py:157} INFO - Started process (PID=469) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:38:42.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:38:42.511+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:38:42.511+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:38:42.519+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:38:42.517+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:38:42.520+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:38:42.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T01:39:12.959+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:39:12.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:39:12.968+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:39:12.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:39:12.976+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:39:12.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:39:12.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:39:12.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T01:39:43.383+0000] {processor.py:157} INFO - Started process (PID=487) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:39:43.385+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:39:43.390+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:39:43.390+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:39:43.398+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:39:43.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:39:43.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:39:43.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.042 seconds
[2023-11-17T01:40:13.870+0000] {processor.py:157} INFO - Started process (PID=496) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:40:13.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:40:13.877+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:40:13.876+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:40:13.884+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:40:13.882+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:40:13.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:40:13.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.041 seconds
[2023-11-17T01:40:44.326+0000] {processor.py:157} INFO - Started process (PID=505) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:40:44.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:40:44.333+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:40:44.332+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:40:44.340+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:40:44.338+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:40:44.341+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:40:44.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T01:41:14.747+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:41:14.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:41:14.754+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:41:14.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:41:14.761+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:41:14.760+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:41:14.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:41:14.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.041 seconds
[2023-11-17T01:41:45.151+0000] {processor.py:157} INFO - Started process (PID=523) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:41:45.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:41:45.155+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:41:45.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:41:45.160+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:41:45.158+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:41:45.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:41:45.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.028 seconds
[2023-11-17T01:42:16.233+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:42:16.236+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:42:16.241+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:42:16.241+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:42:16.249+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:42:16.247+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:42:16.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:42:16.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.044 seconds
[2023-11-17T01:43:57.337+0000] {processor.py:157} INFO - Started process (PID=541) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:43:57.338+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:43:57.342+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:43:57.341+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:43:57.348+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:43:57.346+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:43:57.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:43:57.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.038 seconds
[2023-11-17T01:44:27.789+0000] {processor.py:157} INFO - Started process (PID=550) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:44:27.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:44:27.797+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:44:27.796+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:44:27.812+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:44:27.804+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:44:27.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:44:27.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.064 seconds
[2023-11-17T01:44:58.275+0000] {processor.py:157} INFO - Started process (PID=559) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:44:58.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:44:58.281+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:44:58.281+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:44:58.292+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:44:58.286+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:44:58.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:44:58.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.063 seconds
[2023-11-17T01:45:28.696+0000] {processor.py:157} INFO - Started process (PID=568) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:45:28.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:45:28.714+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:45:28.713+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:45:28.722+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:45:28.719+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:45:28.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:45:28.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.102 seconds
[2023-11-17T01:45:59.248+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:45:59.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:45:59.256+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:45:59.256+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:45:59.264+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:45:59.262+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:45:59.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:45:59.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T01:46:29.750+0000] {processor.py:157} INFO - Started process (PID=586) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:46:29.752+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:46:29.765+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:46:29.764+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:46:29.787+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:46:29.784+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:46:29.788+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:46:29.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.072 seconds
[2023-11-17T01:47:00.382+0000] {processor.py:157} INFO - Started process (PID=595) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:47:00.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:47:00.402+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:47:00.401+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:47:00.412+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:47:00.409+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:47:00.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:47:00.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.117 seconds
[2023-11-17T01:47:30.908+0000] {processor.py:157} INFO - Started process (PID=604) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:47:30.910+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:47:30.914+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:47:30.914+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:47:30.920+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:47:30.918+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:47:30.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:47:30.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.051 seconds
[2023-11-17T01:48:01.580+0000] {processor.py:157} INFO - Started process (PID=613) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:48:01.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:48:01.595+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:48:01.594+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:48:01.611+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:48:01.606+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:48:01.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:48:01.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.066 seconds
[2023-11-17T01:48:32.132+0000] {processor.py:157} INFO - Started process (PID=622) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:48:32.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:48:32.143+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:48:32.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:48:32.149+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:48:32.148+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:48:32.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:48:32.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T01:49:02.609+0000] {processor.py:157} INFO - Started process (PID=631) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:49:02.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:49:02.616+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:49:02.616+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:49:02.624+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:49:02.622+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:49:02.625+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:49:02.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.056 seconds
[2023-11-17T01:49:33.089+0000] {processor.py:157} INFO - Started process (PID=640) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:49:33.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:49:33.097+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:49:33.096+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:49:33.105+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:49:33.103+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:49:33.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:49:33.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.052 seconds
[2023-11-17T01:50:03.635+0000] {processor.py:157} INFO - Started process (PID=649) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:50:03.638+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:50:03.642+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:50:03.642+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:50:03.650+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:50:03.648+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:50:03.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:50:03.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.048 seconds
[2023-11-17T01:50:34.083+0000] {processor.py:157} INFO - Started process (PID=658) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:50:34.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:50:34.092+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:50:34.090+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:50:34.109+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:50:34.105+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:50:34.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:50:34.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.067 seconds
[2023-11-17T01:51:04.590+0000] {processor.py:157} INFO - Started process (PID=667) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:51:04.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:51:04.596+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:51:04.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:51:04.603+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:51:04.601+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:51:04.604+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:51:04.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.058 seconds
[2023-11-17T01:51:35.074+0000] {processor.py:157} INFO - Started process (PID=676) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:51:35.075+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:51:35.079+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:51:35.079+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:51:35.085+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:51:35.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:51:35.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:51:35.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.054 seconds
[2023-11-17T01:52:05.620+0000] {processor.py:157} INFO - Started process (PID=685) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:52:05.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:52:05.628+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:52:05.628+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:52:05.637+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:52:05.635+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:52:05.638+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:52:05.657+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T01:52:36.135+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:52:36.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:52:36.151+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:52:36.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:52:36.159+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:52:36.157+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:52:36.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:52:36.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.069 seconds
[2023-11-17T01:53:06.717+0000] {processor.py:157} INFO - Started process (PID=704) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:53:06.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:53:06.726+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:53:06.724+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:53:06.737+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:53:06.735+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:53:06.738+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:53:06.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.050 seconds
[2023-11-17T01:53:37.185+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:53:37.187+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:53:37.192+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:53:37.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:53:37.199+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:53:37.197+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:53:37.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:53:37.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.044 seconds
[2023-11-17T01:54:07.661+0000] {processor.py:157} INFO - Started process (PID=722) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:54:07.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:54:07.668+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:54:07.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:54:07.675+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:54:07.673+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:54:07.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:54:07.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.039 seconds
[2023-11-17T01:54:38.086+0000] {processor.py:157} INFO - Started process (PID=731) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:54:38.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:54:38.092+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:54:38.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:54:38.099+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:54:38.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:54:38.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:54:38.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.054 seconds
[2023-11-17T01:55:08.578+0000] {processor.py:157} INFO - Started process (PID=740) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:55:08.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:55:08.585+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:55:08.585+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:55:08.594+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:55:08.591+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:55:08.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:55:08.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.053 seconds
[2023-11-17T01:55:39.047+0000] {processor.py:157} INFO - Started process (PID=749) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:55:39.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:55:39.056+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:55:39.056+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:55:39.064+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:55:39.062+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:55:39.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:55:39.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T01:56:09.531+0000] {processor.py:157} INFO - Started process (PID=759) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:56:09.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:56:09.539+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:56:09.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:56:09.546+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:56:09.544+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:56:09.547+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:56:09.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.066 seconds
[2023-11-17T01:56:39.989+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:56:39.992+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:56:39.997+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:56:39.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:56:40.003+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:56:40.002+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:56:40.004+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:56:40.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.048 seconds
[2023-11-17T01:57:10.542+0000] {processor.py:157} INFO - Started process (PID=777) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:57:10.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:57:10.551+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:57:10.550+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:57:10.559+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:57:10.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:57:10.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:57:10.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.048 seconds
[2023-11-17T01:57:41.001+0000] {processor.py:157} INFO - Started process (PID=787) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:57:41.004+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:57:41.009+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:57:41.009+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:57:41.017+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:57:41.014+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:57:41.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:57:41.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.056 seconds
[2023-11-17T01:58:11.588+0000] {processor.py:157} INFO - Started process (PID=796) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:58:11.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:58:11.594+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:58:11.593+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:58:11.601+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:58:11.599+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:58:11.602+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:58:11.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.059 seconds
[2023-11-17T01:58:42.113+0000] {processor.py:157} INFO - Started process (PID=805) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:58:42.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:58:42.121+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:58:42.120+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:58:42.136+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:58:42.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:58:42.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:58:42.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T01:59:12.659+0000] {processor.py:157} INFO - Started process (PID=814) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:59:12.663+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:59:12.668+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:59:12.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:59:12.675+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:59:12.673+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:59:12.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:59:12.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.064 seconds
[2023-11-17T01:59:43.249+0000] {processor.py:157} INFO - Started process (PID=823) to work on /opt/airflow/dags/untitled.py
[2023-11-17T01:59:43.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T01:59:43.256+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:59:43.256+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T01:59:43.264+0000] {logging_mixin.py:154} INFO - [2023-11-17T01:59:43.262+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T01:59:43.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T01:59:43.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.046 seconds
[2023-11-17T02:00:13.732+0000] {processor.py:157} INFO - Started process (PID=832) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:00:13.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:00:13.739+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:00:13.739+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:00:13.747+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:00:13.745+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:00:13.747+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:00:13.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.064 seconds
[2023-11-17T02:00:44.249+0000] {processor.py:157} INFO - Started process (PID=841) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:00:44.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:00:44.257+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:00:44.257+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:00:44.264+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:00:44.262+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:00:44.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:00:44.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T02:01:14.729+0000] {processor.py:157} INFO - Started process (PID=850) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:01:14.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:01:14.736+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:01:14.736+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:01:14.743+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:01:14.742+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:01:14.744+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:01:14.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.060 seconds
[2023-11-17T02:01:45.257+0000] {processor.py:157} INFO - Started process (PID=859) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:01:45.260+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:01:45.265+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:01:45.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:01:45.272+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:01:45.270+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:01:45.273+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:01:45.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.050 seconds
[2023-11-17T02:02:15.885+0000] {processor.py:157} INFO - Started process (PID=867) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:02:15.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:02:15.891+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:02:15.891+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:02:15.897+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:02:15.895+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:02:15.897+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:02:15.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.050 seconds
[2023-11-17T02:02:46.476+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:02:46.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:02:46.482+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:02:46.481+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:02:46.488+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:02:46.486+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:02:46.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:02:46.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.042 seconds
[2023-11-17T02:03:16.958+0000] {processor.py:157} INFO - Started process (PID=885) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:03:16.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:03:16.964+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:03:16.964+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:03:16.973+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:03:16.970+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:03:16.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:03:17.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.063 seconds
[2023-11-17T02:03:47.477+0000] {processor.py:157} INFO - Started process (PID=894) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:03:47.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:03:47.484+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:03:47.483+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:03:47.491+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:03:47.489+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:03:47.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:03:47.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T02:04:17.976+0000] {processor.py:157} INFO - Started process (PID=903) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:04:17.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:04:17.981+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:04:17.981+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:04:17.987+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:04:17.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:04:17.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:04:18.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.040 seconds
[2023-11-17T02:04:48.440+0000] {processor.py:157} INFO - Started process (PID=912) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:04:48.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:04:48.451+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:04:48.450+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:04:48.457+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:04:48.456+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:04:48.458+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:04:48.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.050 seconds
[2023-11-17T02:05:18.937+0000] {processor.py:157} INFO - Started process (PID=921) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:05:18.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:05:18.943+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:05:18.943+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:05:18.950+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:05:18.948+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:05:18.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:05:18.988+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.059 seconds
[2023-11-17T02:05:49.451+0000] {processor.py:157} INFO - Started process (PID=930) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:05:49.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:05:49.461+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:05:49.460+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:05:49.470+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:05:49.467+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:05:49.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:05:49.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.058 seconds
[2023-11-17T02:06:19.951+0000] {processor.py:157} INFO - Started process (PID=939) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:06:19.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:06:19.960+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:06:19.959+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:06:19.968+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:06:19.966+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:06:19.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:06:20.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.057 seconds
[2023-11-17T02:06:50.497+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:06:50.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:06:50.505+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:06:50.505+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:06:50.512+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:06:50.510+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:06:50.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:06:50.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.051 seconds
[2023-11-17T02:07:21.013+0000] {processor.py:157} INFO - Started process (PID=957) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:07:21.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:07:21.019+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:07:21.019+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:07:21.026+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:07:21.024+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:07:21.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:07:21.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.065 seconds
[2023-11-17T02:07:51.560+0000] {processor.py:157} INFO - Started process (PID=966) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:07:51.563+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:07:51.567+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:07:51.567+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:07:51.580+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:07:51.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:07:51.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:07:51.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.070 seconds
[2023-11-17T02:08:22.105+0000] {processor.py:157} INFO - Started process (PID=975) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:08:22.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:08:22.111+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:08:22.110+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:08:22.118+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:08:22.116+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:08:22.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:08:22.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.051 seconds
[2023-11-17T02:08:52.581+0000] {processor.py:157} INFO - Started process (PID=984) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:08:52.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:08:52.589+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:08:52.588+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:08:52.597+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:08:52.594+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:08:52.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:08:52.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.046 seconds
[2023-11-17T02:09:23.291+0000] {processor.py:157} INFO - Started process (PID=996) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:09:23.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:09:23.299+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:09:23.298+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:09:23.305+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:09:23.304+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:09:23.306+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:09:23.323+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.038 seconds
[2023-11-17T02:09:53.732+0000] {processor.py:157} INFO - Started process (PID=1005) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:09:53.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:09:53.744+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:09:53.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:09:53.750+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:09:53.748+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:09:53.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:09:53.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.047 seconds
[2023-11-17T02:10:24.233+0000] {processor.py:157} INFO - Started process (PID=1014) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:10:24.234+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:10:24.236+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:10:24.235+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:10:24.243+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:10:24.241+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:10:24.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:10:24.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
[2023-11-17T02:10:54.667+0000] {processor.py:157} INFO - Started process (PID=1023) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:10:54.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:10:54.671+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:10:54.670+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:10:54.679+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:10:54.677+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:10:54.679+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:10:54.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.046 seconds
[2023-11-17T02:11:25.237+0000] {processor.py:157} INFO - Started process (PID=1032) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:11:25.239+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:11:25.243+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:11:25.241+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:11:25.258+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:11:25.253+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:11:25.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:11:25.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.047 seconds
[2023-11-17T02:12:15.499+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:12:15.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:12:15.503+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:12:15.502+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:12:15.513+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:12:15.509+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:12:15.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:12:15.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.053 seconds
[2023-11-17T02:12:45.927+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:12:45.929+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:12:45.933+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:12:45.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:12:45.940+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:12:45.937+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:12:45.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:12:45.968+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.047 seconds
[2023-11-17T02:13:16.373+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/untitled.py
[2023-11-17T02:13:16.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/untitled.py for tasks to queue
[2023-11-17T02:13:16.378+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:13:16.378+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/untitled.py
[2023-11-17T02:13:16.383+0000] {logging_mixin.py:154} INFO - [2023-11-17T02:13:16.381+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/untitled.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/untitled.py", line 8, in <module>
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
NameError: name 'pendulum' is not defined
[2023-11-17T02:13:16.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/untitled.py
[2023-11-17T02:13:16.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/untitled.py took 0.043 seconds
