[2023-11-17T01:21:24.171+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-17T01:21:15.690338+00:00 [queued]>
[2023-11-17T01:21:24.175+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-17T01:21:15.690338+00:00 [queued]>
[2023-11-17T01:21:24.175+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-17T01:21:24.181+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): step2> on 2023-11-17 01:21:15.690338+00:00
[2023-11-17T01:21:24.184+0000] {standard_task_runner.py:57} INFO - Started process 205 to run task
[2023-11-17T01:21:24.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'step2', 'manual__2023-11-17T01:21:15.690338+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpheyho2x8']
[2023-11-17T01:21:24.187+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask step2
[2023-11-17T01:21:24.210+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.step2 manual__2023-11-17T01:21:15.690338+00:00 [running]> on host c45f18363108
[2023-11-17T01:21:24.246+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='step2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-17T01:21:15.690338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-17T01:21:15.690338+00:00'
[2023-11-17T01:21:24.247+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-17T01:21:24.247+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls /opt/***/data/2023-11-17/downloads']
[2023-11-17T01:21:24.253+0000] {subprocess.py:86} INFO - Output:
[2023-11-17T01:21:24.263+0000] {subprocess.py:93} INFO - ls: cannot access '/opt/***/data/2023-11-17/downloads': No such file or directory
[2023-11-17T01:21:24.263+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-17T01:21:24.269+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-17T01:21:24.271+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=step2, execution_date=20231117T012115, start_date=20231117T012124, end_date=20231117T012124
[2023-11-17T01:21:24.276+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task step2 (Bash command failed. The command returned a non-zero exit code 2.; 205)
[2023-11-17T01:21:24.320+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-17T01:21:24.329+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
