[2023-11-21T00:54:42.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-21T00:54:33.600577+00:00 [queued]>
[2023-11-21T00:54:42.515+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform manual__2023-11-21T00:54:33.600577+00:00 [queued]>
[2023-11-21T00:54:42.515+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T00:54:42.521+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-21 00:54:33.600577+00:00
[2023-11-21T00:54:42.525+0000] {standard_task_runner.py:57} INFO - Started process 262 to run task
[2023-11-21T00:54:42.528+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'manual__2023-11-21T00:54:33.600577+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpyt4frppg']
[2023-11-21T00:54:42.530+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask transform
[2023-11-21T00:54:42.555+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform manual__2023-11-21T00:54:33.600577+00:00 [running]> on host 39ee77aaeaf9
[2023-11-21T00:54:42.757+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:54:33.600577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T00:54:33.600577+00:00'
[2023-11-21T00:54:43.204+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_scripts/transform.py:67: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['ts'] = pd.to_datetime(data.DateTime)

[2023-11-21T00:54:49.799+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 21, in transform_data
    new_data = prep_data(new_data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 75, in prep_data
    data = data.drop_duplicates(subset=['animal_id'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6522, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6654, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['animal_id'], dtype='object')
[2023-11-21T00:54:49.815+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231121T005433, start_date=20231121T005442, end_date=20231121T005449
[2023-11-21T00:54:49.837+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task transform (Index(['animal_id'], dtype='object'); 262)
[2023-11-21T00:54:49.882+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T00:54:49.904+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
